// Chapter14/node-angular/src/app/navbar.component.ts
import { Component, Injectable, EventEmitter, Output } from '@angular/core';
import { Http, Response, Headers, RequestOptions } from '@angular/http';

interface IButtonName {
    ButtonName : string;
}

@Component( {
    moduleId : module.id,
    selector: 'navbar-component',
    templateUrl: './navbar.component.html'
})


@Injectable()
export class NavbarComponent {
    menuItems : IButtonName [];

    @Output() notify: EventEmitter<string> 
        = new EventEmitter<string>();

 constructor (private http: Http) {
    console.log('AppComponent constructor');
    this.http.get('/menuitems')
     .map(res => res.text())
     .subscribe(
      (data) => {
        console.log(`got : ${data}`);
        let jsonResponse = JSON.parse(data);
        this.menuItems = jsonResponse.menuItems;
      },
      err => {
        console.log(`error : ${err}`);
      },
      () => {
        console.log(`success`);
      }
    );
  }

  navClicked(item : IButtonName) {
    this.notify.emit(`${item.ButtonName}`);
  }

}
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
        <a class="navbar-brand">Home</a>
        <ul class="nav navbar-nav">
            
            <li *ngFor="let item of menuItems; let i = index" >
                <a href="#" id="menuItem_{{item.ButtonName}}"
                    (click)="navClicked(item)">{{item.ButtonName}}
                </a>
            </li> 
        </ul>
    </div>
</nav>

// Chapter13/node_react/app/NavBar.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';

export class MenuItem {
    ButtonName: string;
}

export class NavBarProps {
    menuItems ? : MenuItem [] ;
}

export default class NavBar 
extends React.Component<NavBarProps, {}> {
    state: NavBarProps;
constructor(props?: NavBarProps) {
    super(props);
    this.state = {menuItems : [  ]};
    fetch('/menuitems')
    .then( (response) => { 
            return response.json(); }
            )
    .then( (json) => {
            this.setState({ menuItems : json.menuItems});
        })
    .catch( (err) => {
            console.log(`err : ${err}`);
    });
}
    render() {
return <div>       
    <nav 
        className="navbar navbar-default navbar-fixed-top navbar-inverse">
        <div className="container-fluid">
            <a className="navbar-brand">Home</a>
            <ul className="nav navbar-nav">
                { this.state.menuItems.map( function (item, i) {
                    return (
                        <li key={i} 
                            className="nav-item nav-link active">
                            <a href="#" >{item.ButtonName}</a></li>
                    );
                }, this)}

            </ul>
        </div>
    </nav>
</div>;

    }
}
