// Chapter07/angular2_sample/src/app/app.component.ts
import { Component } from '@angular/core';

export class ClickableItem {
    displayName: string;
    id: number;
}

let ClickableItemArray : ClickableItem[] = [
    { id: 1, displayName : "firstItem"},
    { id: 2, displayName : "secondItem"},
    { id: 3, displayName : "thirdItem"},
];

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'hello angular !';
  items = ClickableItemArray;
  onSelect(selectedItem: ClickableItem) {
        alert(`onSelect : id=${selectedItem.id} 
            displayName=${selectedItem.displayName}`);
    }
}

<h1>
  {{title}}
</h1>

<ul>
    <li *ngFor="let item of items"
      (click)="onSelect(item)">
        <button>
            {{item.displayName}}
        </button>
    </li>
</ul>

// Chapter09/react_test/app/index.tsx
import * as React from "react";
import * as ReactDOM from "react-dom";

import { ArrayView, ClickableItem } 
    from "./ReactApp";

let ClickableItemArray : ClickableItem[] = [
    { id: 1, displayName : "firstItem"},
    { id: 2, displayName : "secondItem"},
    { id: 3, displayName : "thirdItem"},
]; 

ReactDOM.render(
    <ArrayView items={ClickableItemArray} 
        title="Select an option:"  />,
);
